apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: mluukkai-example-app-docker
  labels:
    app: mluukkai-example-app-docker

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: mluukkai-example-app-docker

  template:
    metadata:
      labels:
        app: mluukkai-example-app-docker
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/mluukkai-example-app-docker:latest
          name: mluukkai-example-app-docker
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        service: workshop